// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParlanceBackend.Data;

namespace ParlanceBackend.Migrations
{
    [DbContext(typeof(ProjectContext))]
    [Migration("20210824105651_InitialSchema")]
    partial class InitialSchema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("ParlanceBackend.Models.AllowedLanguages", b =>
                {
                    b.Property<ulong>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LanguageIdentifier")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("LanguageIdentifier");

                    b.ToTable("AllowedLanguages");
                });

            modelBuilder.Entity("ParlanceBackend.Models.Language", b =>
                {
                    b.Property<string>("Identifier")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Identifier");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Identifier = "af-ZA",
                            Name = "Afrikaans (South Africa)"
                        },
                        new
                        {
                            Identifier = "am-ET",
                            Name = "Amharic (Ethiopia)"
                        },
                        new
                        {
                            Identifier = "ar-AE",
                            Name = "Arabic (United Arab Emirates)"
                        },
                        new
                        {
                            Identifier = "ar-BH",
                            Name = "Arabic (Bahrain)"
                        },
                        new
                        {
                            Identifier = "ar-DZ",
                            Name = "Arabic (Algeria)"
                        },
                        new
                        {
                            Identifier = "ar-EG",
                            Name = "Arabic (Egypt)"
                        },
                        new
                        {
                            Identifier = "ar-IQ",
                            Name = "Arabic (Iraq)"
                        },
                        new
                        {
                            Identifier = "ar-JO",
                            Name = "Arabic (Jordan)"
                        },
                        new
                        {
                            Identifier = "ar-KW",
                            Name = "Arabic (Kuwait)"
                        },
                        new
                        {
                            Identifier = "ar-LB",
                            Name = "Arabic (Lebanon)"
                        },
                        new
                        {
                            Identifier = "ar-LY",
                            Name = "Arabic (Libya)"
                        },
                        new
                        {
                            Identifier = "ar-MA",
                            Name = "Arabic (Morocco)"
                        },
                        new
                        {
                            Identifier = "ar-OM",
                            Name = "Arabic (Oman)"
                        },
                        new
                        {
                            Identifier = "ar-QA",
                            Name = "Arabic (Qatar)"
                        },
                        new
                        {
                            Identifier = "ar-SA",
                            Name = "Arabic (Saudi Arabia)"
                        },
                        new
                        {
                            Identifier = "ar-SY",
                            Name = "Arabic (Syria)"
                        },
                        new
                        {
                            Identifier = "ar-TN",
                            Name = "Arabic (Tunisia)"
                        },
                        new
                        {
                            Identifier = "ar-YE",
                            Name = "Arabic (Yemen)"
                        },
                        new
                        {
                            Identifier = "as-IN",
                            Name = "Assamese (India)"
                        },
                        new
                        {
                            Identifier = "az-AZ",
                            Name = "Azerbaijani (Cyrillic, Azerbaijan)"
                        },
                        new
                        {
                            Identifier = "be-BY",
                            Name = "Belarusian (Belarus)"
                        },
                        new
                        {
                            Identifier = "bg-BG",
                            Name = "Bulgarian (Bulgaria)"
                        },
                        new
                        {
                            Identifier = "bn-BD",
                            Name = "Bengali (Bangladesh)"
                        },
                        new
                        {
                            Identifier = "bn-IN",
                            Name = "Bengali (India)"
                        },
                        new
                        {
                            Identifier = "bo-CN",
                            Name = "Tibetan (China)"
                        },
                        new
                        {
                            Identifier = "br-FR",
                            Name = "Breton (France)"
                        },
                        new
                        {
                            Identifier = "bs-BA",
                            Name = "Bosnian (Cyrillic, Bosnia & Herzegovina)"
                        },
                        new
                        {
                            Identifier = "ca-ES",
                            Name = "Catalan (Spain)"
                        },
                        new
                        {
                            Identifier = "cs-CZ",
                            Name = "Czech (Czechia)"
                        },
                        new
                        {
                            Identifier = "cy-GB",
                            Name = "Welsh (United Kingdom)"
                        },
                        new
                        {
                            Identifier = "da-DK",
                            Name = "Danish (Denmark)"
                        },
                        new
                        {
                            Identifier = "de-AT",
                            Name = "German (Austria)"
                        },
                        new
                        {
                            Identifier = "de-CH",
                            Name = "German (Switzerland)"
                        },
                        new
                        {
                            Identifier = "de-DE",
                            Name = "German (Germany)"
                        },
                        new
                        {
                            Identifier = "de-LI",
                            Name = "German (Liechtenstein)"
                        },
                        new
                        {
                            Identifier = "de-LU",
                            Name = "German (Luxembourg)"
                        },
                        new
                        {
                            Identifier = "dsb-DE",
                            Name = "Lower Sorbian (Germany)"
                        },
                        new
                        {
                            Identifier = "dz-BT",
                            Name = "Dzongkha (Bhutan)"
                        },
                        new
                        {
                            Identifier = "el-GR",
                            Name = "Greek (Greece)"
                        },
                        new
                        {
                            Identifier = "en-AU",
                            Name = "English (Australia)"
                        },
                        new
                        {
                            Identifier = "en-BZ",
                            Name = "English (Belize)"
                        },
                        new
                        {
                            Identifier = "en-CA",
                            Name = "English (Canada)"
                        },
                        new
                        {
                            Identifier = "en-GB",
                            Name = "English (United Kingdom)"
                        },
                        new
                        {
                            Identifier = "en-HK",
                            Name = "English (Hong Kong SAR China)"
                        },
                        new
                        {
                            Identifier = "en-IE",
                            Name = "English (Ireland)"
                        },
                        new
                        {
                            Identifier = "en-IN",
                            Name = "English (India)"
                        },
                        new
                        {
                            Identifier = "en-JM",
                            Name = "English (Jamaica)"
                        },
                        new
                        {
                            Identifier = "en-MY",
                            Name = "English (Malaysia)"
                        },
                        new
                        {
                            Identifier = "en-NZ",
                            Name = "English (New Zealand)"
                        },
                        new
                        {
                            Identifier = "en-PH",
                            Name = "English (Philippines)"
                        },
                        new
                        {
                            Identifier = "en-SG",
                            Name = "English (Singapore)"
                        },
                        new
                        {
                            Identifier = "en-TT",
                            Name = "English (Trinidad & Tobago)"
                        },
                        new
                        {
                            Identifier = "en-US",
                            Name = "English (United States)"
                        },
                        new
                        {
                            Identifier = "en-ZA",
                            Name = "English (South Africa)"
                        },
                        new
                        {
                            Identifier = "en-ZW",
                            Name = "English (Zimbabwe)"
                        },
                        new
                        {
                            Identifier = "es-419",
                            Name = "Spanish (Latin America)"
                        },
                        new
                        {
                            Identifier = "es-AR",
                            Name = "Spanish (Argentina)"
                        },
                        new
                        {
                            Identifier = "es-BO",
                            Name = "Spanish (Bolivia)"
                        },
                        new
                        {
                            Identifier = "es-CL",
                            Name = "Spanish (Chile)"
                        },
                        new
                        {
                            Identifier = "es-CO",
                            Name = "Spanish (Colombia)"
                        },
                        new
                        {
                            Identifier = "es-CR",
                            Name = "Spanish (Costa Rica)"
                        },
                        new
                        {
                            Identifier = "es-CU",
                            Name = "Spanish (Cuba)"
                        },
                        new
                        {
                            Identifier = "es-DO",
                            Name = "Spanish (Dominican Republic)"
                        },
                        new
                        {
                            Identifier = "es-EC",
                            Name = "Spanish (Ecuador)"
                        },
                        new
                        {
                            Identifier = "es-ES",
                            Name = "Spanish (Spain)"
                        },
                        new
                        {
                            Identifier = "es-GT",
                            Name = "Spanish (Guatemala)"
                        },
                        new
                        {
                            Identifier = "es-HN",
                            Name = "Spanish (Honduras)"
                        },
                        new
                        {
                            Identifier = "es-MX",
                            Name = "Spanish (Mexico)"
                        },
                        new
                        {
                            Identifier = "es-NI",
                            Name = "Spanish (Nicaragua)"
                        },
                        new
                        {
                            Identifier = "es-PA",
                            Name = "Spanish (Panama)"
                        },
                        new
                        {
                            Identifier = "es-PE",
                            Name = "Spanish (Peru)"
                        },
                        new
                        {
                            Identifier = "es-PR",
                            Name = "Spanish (Puerto Rico)"
                        },
                        new
                        {
                            Identifier = "es-PY",
                            Name = "Spanish (Paraguay)"
                        },
                        new
                        {
                            Identifier = "es-SV",
                            Name = "Spanish (El Salvador)"
                        },
                        new
                        {
                            Identifier = "es-US",
                            Name = "Spanish (United States)"
                        },
                        new
                        {
                            Identifier = "es-UY",
                            Name = "Spanish (Uruguay)"
                        },
                        new
                        {
                            Identifier = "es-VE",
                            Name = "Spanish (Venezuela)"
                        },
                        new
                        {
                            Identifier = "et-EE",
                            Name = "Estonian (Estonia)"
                        },
                        new
                        {
                            Identifier = "eu-ES",
                            Name = "Basque (Spain)"
                        },
                        new
                        {
                            Identifier = "fa-IR",
                            Name = "Persian (Iran)"
                        },
                        new
                        {
                            Identifier = "ff-SN",
                            Name = "Fulah (Latin, Senegal)"
                        },
                        new
                        {
                            Identifier = "fi-FI",
                            Name = "Finnish (Finland)"
                        },
                        new
                        {
                            Identifier = "fil-PH",
                            Name = "Filipino (Philippines)"
                        },
                        new
                        {
                            Identifier = "fo-FO",
                            Name = "Faroese (Faroe Islands)"
                        },
                        new
                        {
                            Identifier = "fr-BE",
                            Name = "French (Belgium)"
                        },
                        new
                        {
                            Identifier = "fr-CA",
                            Name = "French (Canada)"
                        },
                        new
                        {
                            Identifier = "fr-CD",
                            Name = "French (Congo - Kinshasa)"
                        },
                        new
                        {
                            Identifier = "fr-CH",
                            Name = "French (Switzerland)"
                        },
                        new
                        {
                            Identifier = "fr-CI",
                            Name = "French (Côte d’Ivoire)"
                        },
                        new
                        {
                            Identifier = "fr-CM",
                            Name = "French (Cameroon)"
                        },
                        new
                        {
                            Identifier = "fr-FR",
                            Name = "French (France)"
                        },
                        new
                        {
                            Identifier = "fr-HT",
                            Name = "French (Haiti)"
                        },
                        new
                        {
                            Identifier = "fr-LU",
                            Name = "French (Luxembourg)"
                        },
                        new
                        {
                            Identifier = "fr-MA",
                            Name = "French (Morocco)"
                        },
                        new
                        {
                            Identifier = "fr-MC",
                            Name = "French (Monaco)"
                        },
                        new
                        {
                            Identifier = "fr-ML",
                            Name = "French (Mali)"
                        },
                        new
                        {
                            Identifier = "fr-RE",
                            Name = "French (Réunion)"
                        },
                        new
                        {
                            Identifier = "fr-SN",
                            Name = "French (Senegal)"
                        },
                        new
                        {
                            Identifier = "fy-NL",
                            Name = "Western Frisian (Netherlands)"
                        },
                        new
                        {
                            Identifier = "ga-IE",
                            Name = "Irish (Ireland)"
                        },
                        new
                        {
                            Identifier = "gd-GB",
                            Name = "Scottish Gaelic (United Kingdom)"
                        },
                        new
                        {
                            Identifier = "gl-ES",
                            Name = "Galician (Spain)"
                        },
                        new
                        {
                            Identifier = "gsw-FR",
                            Name = "Swiss German (France)"
                        },
                        new
                        {
                            Identifier = "gu-IN",
                            Name = "Gujarati (India)"
                        },
                        new
                        {
                            Identifier = "haw-US",
                            Name = "Hawaiian (United States)"
                        },
                        new
                        {
                            Identifier = "he-IL",
                            Name = "Hebrew (Israel)"
                        },
                        new
                        {
                            Identifier = "hi-IN",
                            Name = "Hindi (India)"
                        },
                        new
                        {
                            Identifier = "hr-BA",
                            Name = "Croatian (Bosnia & Herzegovina)"
                        },
                        new
                        {
                            Identifier = "hr-HR",
                            Name = "Croatian (Croatia)"
                        },
                        new
                        {
                            Identifier = "hsb-DE",
                            Name = "Upper Sorbian (Germany)"
                        },
                        new
                        {
                            Identifier = "hu-HU",
                            Name = "Hungarian (Hungary)"
                        },
                        new
                        {
                            Identifier = "hy-AM",
                            Name = "Armenian (Armenia)"
                        },
                        new
                        {
                            Identifier = "id-ID",
                            Name = "Indonesian (Indonesia)"
                        },
                        new
                        {
                            Identifier = "ig-NG",
                            Name = "Igbo (Nigeria)"
                        },
                        new
                        {
                            Identifier = "ii-CN",
                            Name = "Sichuan Yi (China)"
                        },
                        new
                        {
                            Identifier = "is-IS",
                            Name = "Icelandic (Iceland)"
                        },
                        new
                        {
                            Identifier = "it-CH",
                            Name = "Italian (Switzerland)"
                        },
                        new
                        {
                            Identifier = "it-IT",
                            Name = "Italian (Italy)"
                        },
                        new
                        {
                            Identifier = "ja-JP",
                            Name = "Japanese (Japan)"
                        },
                        new
                        {
                            Identifier = "ka-GE",
                            Name = "Georgian (Georgia)"
                        },
                        new
                        {
                            Identifier = "kk-KZ",
                            Name = "Kazakh (Kazakhstan)"
                        },
                        new
                        {
                            Identifier = "kl-GL",
                            Name = "Kalaallisut (Greenland)"
                        },
                        new
                        {
                            Identifier = "km-KH",
                            Name = "Khmer (Cambodia)"
                        },
                        new
                        {
                            Identifier = "kn-IN",
                            Name = "Kannada (India)"
                        },
                        new
                        {
                            Identifier = "ko-KR",
                            Name = "Korean (South Korea)"
                        },
                        new
                        {
                            Identifier = "kok-IN",
                            Name = "Konkani (India)"
                        },
                        new
                        {
                            Identifier = "ky-KG",
                            Name = "Kyrgyz (Kyrgyzstan)"
                        },
                        new
                        {
                            Identifier = "lb-LU",
                            Name = "Luxembourgish (Luxembourg)"
                        },
                        new
                        {
                            Identifier = "lo-LA",
                            Name = "Lao (Laos)"
                        },
                        new
                        {
                            Identifier = "lt-LT",
                            Name = "Lithuanian (Lithuania)"
                        },
                        new
                        {
                            Identifier = "lv-LV",
                            Name = "Latvian (Latvia)"
                        },
                        new
                        {
                            Identifier = "mi-NZ",
                            Name = "Maori (New Zealand)"
                        },
                        new
                        {
                            Identifier = "mk-MK",
                            Name = "Macedonian (North Macedonia)"
                        },
                        new
                        {
                            Identifier = "ml-IN",
                            Name = "Malayalam (India)"
                        },
                        new
                        {
                            Identifier = "mn-MN",
                            Name = "Mongolian (Mongolia)"
                        },
                        new
                        {
                            Identifier = "mr-IN",
                            Name = "Marathi (India)"
                        },
                        new
                        {
                            Identifier = "ms-BN",
                            Name = "Malay (Brunei)"
                        },
                        new
                        {
                            Identifier = "ms-MY",
                            Name = "Malay (Malaysia)"
                        },
                        new
                        {
                            Identifier = "mt-MT",
                            Name = "Maltese (Malta)"
                        },
                        new
                        {
                            Identifier = "my-MM",
                            Name = "Burmese (Myanmar [Burma])"
                        },
                        new
                        {
                            Identifier = "nb-NO",
                            Name = "Norwegian Bokmål (Norway)"
                        },
                        new
                        {
                            Identifier = "ne-IN",
                            Name = "Nepali (India)"
                        },
                        new
                        {
                            Identifier = "ne-NP",
                            Name = "Nepali (Nepal)"
                        },
                        new
                        {
                            Identifier = "nl-BE",
                            Name = "Dutch (Belgium)"
                        },
                        new
                        {
                            Identifier = "nl-NL",
                            Name = "Dutch (Netherlands)"
                        },
                        new
                        {
                            Identifier = "nn-NO",
                            Name = "Norwegian Nynorsk (Norway)"
                        },
                        new
                        {
                            Identifier = "om-ET",
                            Name = "Oromo (Ethiopia)"
                        },
                        new
                        {
                            Identifier = "or-IN",
                            Name = "Odia (India)"
                        },
                        new
                        {
                            Identifier = "pa-PK",
                            Name = "Punjabi (Arabic, Pakistan)"
                        },
                        new
                        {
                            Identifier = "pl-PL",
                            Name = "Polish (Poland)"
                        },
                        new
                        {
                            Identifier = "ps-AF",
                            Name = "Pashto (Afghanistan)"
                        },
                        new
                        {
                            Identifier = "pt-BR",
                            Name = "Portuguese (Brazil)"
                        },
                        new
                        {
                            Identifier = "pt-PT",
                            Name = "Portuguese (Portugal)"
                        },
                        new
                        {
                            Identifier = "rm-CH",
                            Name = "Romansh (Switzerland)"
                        },
                        new
                        {
                            Identifier = "ro-MD",
                            Name = "Romanian (Moldova)"
                        },
                        new
                        {
                            Identifier = "ro-RO",
                            Name = "Romanian (Romania)"
                        },
                        new
                        {
                            Identifier = "ru-MD",
                            Name = "Russian (Moldova)"
                        },
                        new
                        {
                            Identifier = "ru-RU",
                            Name = "Russian (Russia)"
                        },
                        new
                        {
                            Identifier = "rw-RW",
                            Name = "Kinyarwanda (Rwanda)"
                        },
                        new
                        {
                            Identifier = "sa-IN",
                            Name = "Sanskrit (India)"
                        },
                        new
                        {
                            Identifier = "sah-RU",
                            Name = "Yakut (Russia)"
                        },
                        new
                        {
                            Identifier = "sd-PK",
                            Name = "Sindhi (Arabic, Pakistan)"
                        },
                        new
                        {
                            Identifier = "sd-IN",
                            Name = "Sindhi (Devanagari, India)"
                        },
                        new
                        {
                            Identifier = "se-FI",
                            Name = "Northern Sami (Finland)"
                        },
                        new
                        {
                            Identifier = "se-NO",
                            Name = "Northern Sami (Norway)"
                        },
                        new
                        {
                            Identifier = "se-SE",
                            Name = "Northern Sami (Sweden)"
                        },
                        new
                        {
                            Identifier = "si-LK",
                            Name = "Sinhala (Sri Lanka)"
                        },
                        new
                        {
                            Identifier = "sk-SK",
                            Name = "Slovak (Slovakia)"
                        },
                        new
                        {
                            Identifier = "sl-SI",
                            Name = "Slovenian (Slovenia)"
                        },
                        new
                        {
                            Identifier = "smn-FI",
                            Name = "Inari Sami (Finland)"
                        },
                        new
                        {
                            Identifier = "so-SO",
                            Name = "Somali (Somalia)"
                        },
                        new
                        {
                            Identifier = "sq-AL",
                            Name = "Albanian (Albania)"
                        },
                        new
                        {
                            Identifier = "sr-BA",
                            Name = "Serbian (Cyrillic, Bosnia & Herzegovina)"
                        },
                        new
                        {
                            Identifier = "sr-ME",
                            Name = "Serbian (Cyrillic, Montenegro)"
                        },
                        new
                        {
                            Identifier = "sr-RS",
                            Name = "Serbian (Cyrillic, Serbia)"
                        },
                        new
                        {
                            Identifier = "sv-FI",
                            Name = "Swedish (Finland)"
                        },
                        new
                        {
                            Identifier = "sv-SE",
                            Name = "Swedish (Sweden)"
                        },
                        new
                        {
                            Identifier = "sw-KE",
                            Name = "Swahili (Kenya)"
                        },
                        new
                        {
                            Identifier = "ta-IN",
                            Name = "Tamil (India)"
                        },
                        new
                        {
                            Identifier = "ta-LK",
                            Name = "Tamil (Sri Lanka)"
                        },
                        new
                        {
                            Identifier = "te-IN",
                            Name = "Telugu (India)"
                        },
                        new
                        {
                            Identifier = "th-TH",
                            Name = "Thai (Thailand)"
                        },
                        new
                        {
                            Identifier = "ti-ER",
                            Name = "Tigrinya (Eritrea)"
                        },
                        new
                        {
                            Identifier = "ti-ET",
                            Name = "Tigrinya (Ethiopia)"
                        },
                        new
                        {
                            Identifier = "tk-TM",
                            Name = "Turkmen (Turkmenistan)"
                        },
                        new
                        {
                            Identifier = "tr-TR",
                            Name = "Turkish (Turkey)"
                        },
                        new
                        {
                            Identifier = "tt-RU",
                            Name = "Tatar (Russia)"
                        },
                        new
                        {
                            Identifier = "ug-CN",
                            Name = "Uyghur (China)"
                        },
                        new
                        {
                            Identifier = "uk-UA",
                            Name = "Ukrainian (Ukraine)"
                        },
                        new
                        {
                            Identifier = "ur-IN",
                            Name = "Urdu (India)"
                        },
                        new
                        {
                            Identifier = "ur-PK",
                            Name = "Urdu (Pakistan)"
                        },
                        new
                        {
                            Identifier = "uz-UZ",
                            Name = "Uzbek (Cyrillic, Uzbekistan)"
                        },
                        new
                        {
                            Identifier = "vi-VN",
                            Name = "Vietnamese (Vietnam)"
                        },
                        new
                        {
                            Identifier = "wo-SN",
                            Name = "Wolof (Senegal)"
                        },
                        new
                        {
                            Identifier = "xh-ZA",
                            Name = "Xhosa (South Africa)"
                        },
                        new
                        {
                            Identifier = "yi-001",
                            Name = "Yiddish (World)"
                        },
                        new
                        {
                            Identifier = "yo-NG",
                            Name = "Yoruba (Nigeria)"
                        },
                        new
                        {
                            Identifier = "zu-ZA",
                            Name = "Zulu (South Africa)"
                        });
                });

            modelBuilder.Entity("ParlanceBackend.Models.ProjectPrivate", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Branch")
                        .HasColumnType("TEXT");

                    b.Property<string>("GitCloneUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("ParlanceBackend.Models.Superuser", b =>
                {
                    b.Property<ulong>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId");

                    b.ToTable("Superusers");
                });

            modelBuilder.Entity("ParlanceBackend.Models.AllowedLanguages", b =>
                {
                    b.HasOne("ParlanceBackend.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageIdentifier");

                    b.Navigation("Language");
                });
#pragma warning restore 612, 618
        }
    }
}
